version: '3.8'
services:
  app:
    container_name: 2336_devchalenge_21-api
    restart: never
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    environment:
      DATABASE_URI: 'mongodb://database:27017'
      REDIS_HOST: 'cache'
      REDIS_PORT: '6379'
      WHISPER_URL: 'http://whisper:9000'
      PORT: '8080'
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      - cache
      - whisper

  cache:
    image: redis:7.4-alpine
    container_name: 2336_devchalenge_21-redis
    restart: never 
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - ./cache:/data

  database:
    image: mongo:7.0
    container_name: 2336_devchalenge_21-mongodb
    restart: never
    volumes:
      - './data:/data/db'

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: 2336_devchalenge_21-whisper
    restart: never
    environment:
      ASR_MODEL: base.en
      ASR_ENGINE: openai_whisper
    ports:
      - '9000:9000'
    volumes:
    - ./whisper:/.cache
