version: '3.8'
services:
  app:
    container_name: calls-api
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    environment:
      DATABASE_URI: 'mongodb://database:27017'
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: mongo:7.0
    container_name: calls-mongodb
    restart: no
    volumes:
      - './data:/data/db'
