export const commands = {
  TRANSCRIBE_CALL: 'TRANSCRIBE_AUDIO',
  CLASSIFY_TEXT: 'CLASSIFY_TEXT',
  TOKENIZE_TEXT: 'TOKENIZE_TEXT',
  CATEGORY_CLASSIFY_TEXT: 'CATEGORY_CLASSIFY_TEXT',
  CATEGORY_UPDATE_RESOLVE: 'CATEGORY_UPDATE_RESOLVE',
};
